# https://docs.gradle.org/current/userguide/build_environment.html
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# https://docs.gradle.org/current/userguide/configuration_cache.html
org.gradle.configuration-cache=true

# https://kotlinlang.org/docs/coding-conventions.html
kotlin.code.style=official
